package demo.repository.mapper;

import demo.repository.po.UserView;
import demo.repository.po.UserViewExample;
import java.util.List;

public interface UserViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    long countByExample(UserViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    List<UserView> selectByExample(UserViewExample example);
}