package demo.repository.po;

import com.fasterxml.jackson.annotation.JsonAnyGetter;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_demo
 */
public class Demo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.col1
     *
     * @mbg.generated
     */
    private String col1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.col2
     *
     * @mbg.generated
     */
    private String col2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.col3
     *
     * @mbg.generated
     */
    private String col3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.id
     *
     * @return the value of t_demo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.id
     *
     * @param id the value for t_demo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.col1
     *
     * @return the value of t_demo.col1
     *
     * @mbg.generated
     */
    public String getCol1() {
        return col1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.col1
     *
     * @param col1 the value for t_demo.col1
     *
     * @mbg.generated
     */
    public void setCol1(String col1) {
        this.col1 = col1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.col2
     *
     * @return the value of t_demo.col2
     *
     * @mbg.generated
     */
    public String getCol2() {
        return col2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.col2
     *
     * @param col2 the value for t_demo.col2
     *
     * @mbg.generated
     */
    public void setCol2(String col2) {
        this.col2 = col2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.col3
     *
     * @return the value of t_demo.col3
     *
     * @mbg.generated
     */
    public String getCol3() {
        return col3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.col3
     *
     * @param col3 the value for t_demo.col3
     *
     * @mbg.generated
     */
    public void setCol3(String col3) {
        this.col3 = col3;
    }
}